### ISSUE TITLE
Pasta para arquivos de saída

### ISSUE THREAD

**Issue by MuriloReolonScuzziato** [francisco-povoas/Ferramenta-de-conversao#1]
Criar uma pasta para os arquivos da saída (*.m) não ficarem na raiz da pasta do algoritmo.

**Comment by francisco-povoas** [comment]
Antes de salvar o arquivo gerado .m é verificado se existe o diretorio identificado pelo define de resultado e caso nao exista, o diretório é criado 

A leitura dos arquivos e o resultado irão para diretórios particulares de cada pessoa que estiver rodando a ferramenta em sua máquina, para isso é preciso que cada um configure os caminhos dentro do defines.py

Conforme resolver algumas das pendencias irei detalhar o projeto no README.

Issue resolvida conforme commit:
https://github.com/francisco-povoas/Ferramenta-de-conversao/commit/8ed556dce21f8c00d9279ca13a89c9ffa2c3f2e8
